// SPDX-License-Identifier: MIT
// SPDX-FileCopyrightText: 2025-2026 natyamatsya contributors
//
// `prost` runtime adapter for protobuf codec scaffolding.

use prost::Message as ProstMessage;

use super::protobuf::ProtobufWireMessage;

/// Marker trait for protobuf message types generated by `prost`.
pub trait ProstProtobufMessage: ProstMessage + Default {}

impl<T> ProstProtobufMessage for T where T: ProstMessage + Default {}

impl<T> ProtobufWireMessage for T
where
    T: ProstProtobufMessage,
{
    fn encode(&self) -> Vec<u8> {
        ProstMessage::encode_to_vec(self)
    }

    fn decode(bytes: &[u8]) -> Option<Self> {
        T::decode(bytes).ok()
    }
}
