// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT
// SPDX-FileCopyrightText: 2025-2026 natyamatsya and thoth-ipc contributors
//
// @generated by `tools/abi` from abi/abi.json — DO NOT EDIT.
// Regenerate: cargo run --manifest-path tools/abi/Cargo.toml -- generate --lang cpp
// Target: apple_arm64 / x86_64.

#pragma once
#include <cstddef>
#include <cstdint>

namespace thoth::abi {

inline constexpr const char* abi_version = "1.1.0";

// --- constants ---
/// msg_t payload fragment size (large_msg_limit)
inline constexpr std::size_t data_length = 64;
/// ring slot count (block_[256])
inline constexpr std::size_t ring_size = 256;
/// chunk-size alignment
inline constexpr std::size_t large_msg_align = 1024;
/// chunk slots per chunk size (id_pool capacity)
inline constexpr std::size_t large_msg_cache = 32;
/// per-chunk header = make_align(alignof(max_align_t), sizeof(atomic<cc_t>)=4); align-dependent
#if defined(__APPLE__) && defined(__aarch64__)
inline constexpr std::size_t chunk_header_size = 8;
#else
inline constexpr std::size_t chunk_header_size = 16;
#endif
/// sizeof(chunk_info_t)
inline constexpr std::size_t chunk_info_size = 40;
/// route rc_: low 32 = connection bitmask
inline constexpr std::uint64_t route_ep_mask = 0x00000000ffffffffull;
/// route rc_: epoch increment (high 32)
inline constexpr std::uint64_t route_ep_incr = 0x0000000100000000ull;
/// channel rc_: low 32 = per-reader bitmask
inline constexpr std::uint64_t chan_rc_mask = 0x00000000ffffffffull;
/// channel rc_: low 56 = rc bits + internal read-gen
inline constexpr std::uint64_t chan_ep_mask = 0x00ffffffffffffffull;
/// channel rc_: epoch increment (top byte)
inline constexpr std::uint64_t chan_ep_incr = 0x0100000000000000ull;
/// channel rc_: invert-carry mask
inline constexpr std::uint64_t chan_ic_mask = 0xff000000ffffffffull;
/// channel rc_: internal read-generation increment (bits 32..)
inline constexpr std::uint64_t chan_ic_incr = 0x0000000100000000ull;
/// SyncAbi stamp magic "LISA" (0x4C495341)
inline constexpr std::uint32_t syncabi_magic = 1279873857;
/// SyncAbi backend id: apple_ulock
inline constexpr std::uint32_t syncabi_backend_ulock = 2;
/// secure envelope v1 magic
inline constexpr const char* sipc_magic = "SIPC";
/// secure envelope v1 version
inline constexpr std::uint8_t sipc_version = 1;
/// golden fnv1a_64("__THOTH_SHM__NOTIFY__xchan") for (prefix="", name="xchan")
inline constexpr const char* notify_hash_xchan = "098e889ce378ae04";
/// cross-process sync sidecar shm-name suffix for a mutex; full name = <channel-name> + this suffix (byte-exact across all ports)
inline constexpr const char* sync_abi_suffix_mutex = "__thoth_ipc_sync_abi_mutex";
/// cross-process sync sidecar shm-name suffix for a condition variable; full name = <channel-name> + this suffix (byte-exact across all ports)
inline constexpr const char* sync_abi_suffix_condition = "__thoth_ipc_sync_abi_condition";

// --- enums ---
/// typed codec ids
enum class codec_id : std::uint32_t { flatbuffers = 1, protobuf = 2, capnp = 3 };
/// AEAD algorithm ids (SIPC envelope)
enum class secure_alg : std::uint16_t { aes256gcm = 1, chacha20poly1305 = 2 };

// --- struct layout (byte sizes + field offsets) ---
inline constexpr std::size_t msg_t_size = 80;
inline constexpr std::size_t msg_t_cc_id_off = 0;
inline constexpr std::size_t msg_t_id_off = 4;
inline constexpr std::size_t msg_t_remain_off = 8;
inline constexpr std::size_t msg_t_storage_off = 12;
inline constexpr std::size_t msg_t_payload_off = 16;
inline constexpr std::size_t ring_header_size = 192;
inline constexpr std::size_t ring_header_cc_off = 0;
inline constexpr std::size_t ring_header_lc_off = 4;
inline constexpr std::size_t ring_header_constructed_off = 8;
inline constexpr std::size_t ring_header_cursor_off = 64;
inline constexpr std::size_t ring_header_epoch_off = 128;
#if defined(__APPLE__) && defined(__aarch64__)
inline constexpr std::size_t route_elem_size = 88;
#else
inline constexpr std::size_t route_elem_size = 96;
#endif
inline constexpr std::size_t route_elem_data_off = 0;
inline constexpr std::size_t route_elem_rc_off = 80;
inline constexpr std::size_t channel_elem_size = 96;
inline constexpr std::size_t channel_elem_data_off = 0;
inline constexpr std::size_t channel_elem_rc_off = 80;
inline constexpr std::size_t channel_elem_f_ct_off = 88;
#if defined(__APPLE__) && defined(__aarch64__)
inline constexpr std::size_t route_ring_size = 22784;
#else
inline constexpr std::size_t route_ring_size = 24832;
#endif
inline constexpr std::size_t channel_ring_size = 24832;
inline constexpr std::size_t liveness_slot_size = 16;
inline constexpr std::size_t liveness_slot_pid_off = 0;
inline constexpr std::size_t liveness_slot_start_tok_off = 8;
inline constexpr std::size_t sipc_header_size = 19;
inline constexpr std::size_t sipc_header_magic_off = 0;
inline constexpr std::size_t sipc_header_version_off = 4;
inline constexpr std::size_t sipc_header_alg_id_off = 5;
inline constexpr std::size_t sipc_header_key_id_off = 7;
inline constexpr std::size_t sipc_header_nonce_size_off = 11;
inline constexpr std::size_t sipc_header_tag_size_off = 13;
inline constexpr std::size_t sipc_header_ct_size_off = 15;
inline constexpr std::size_t syncabi_stamp_size = 24;
inline constexpr std::size_t syncabi_stamp_magic_off = 0;
inline constexpr std::size_t syncabi_stamp_ver_major_off = 4;
inline constexpr std::size_t syncabi_stamp_ver_minor_off = 8;
inline constexpr std::size_t syncabi_stamp_backend_id_off = 12;
inline constexpr std::size_t syncabi_stamp_primitive_id_off = 16;
inline constexpr std::size_t syncabi_stamp_payload_size_off = 20;

// --- shm-name goldens (canonical binding — see abi/README.md) ---
#if defined(__APPLE__) && defined(__aarch64__)
inline constexpr const char* name_golden_ring = "__THOTH_SHM__QU_CONN__xchan__64__8";
#else
inline constexpr const char* name_golden_ring = "__THOTH_SHM__QU_CONN__xchan__64__16";
#endif
#if defined(__APPLE__) && defined(__aarch64__)
inline constexpr const char* name_golden_ring_posix = "/__THOTH_SHM___7d090bf7fa85c547";
#else
inline constexpr const char* name_golden_ring_posix = "/__THOTH_SHM__QU_CONN__xchan__64__16";
#endif
inline constexpr const char* name_golden_cc_id = "__THOTH_SHM__CA_CONN__";
inline constexpr const char* name_golden_msg_id = "__THOTH_SHM__AC_CONN__xchan";
inline constexpr const char* name_golden_liveness = "__THOTH_SHM__LV_CONN__xchan";
inline constexpr const char* name_golden_chunk = "__THOTH_SHM__CHUNK_INFO__1024";
inline constexpr const char* name_golden_notify_key = "thoth.ntf.098e889ce378ae04";

} // namespace thoth::abi
