// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception OR MIT
// SPDX-FileCopyrightText: 2025-2026 natyamatsya and thoth-ipc contributors
//
// @generated by `tools/abi` from abi/abi.json — DO NOT EDIT.
// Regenerate: cargo run --manifest-path tools/abi/Cargo.toml -- generate --lang zig
// Target: apple_arm64.

/// ABI contract version (semver; decoupled from the release version). Peers
/// interoperate iff they share the same MAJOR. See abi/README.md#abi-versioning.
pub const abi_version: []const u8 = "1.1.0";

// --- constants ---
/// msg_t payload fragment size (large_msg_limit)
pub const data_length: usize = 64;
/// ring slot count (block_[256])
pub const ring_size: usize = 256;
/// chunk-size alignment
pub const large_msg_align: usize = 1024;
/// chunk slots per chunk size (id_pool capacity)
pub const large_msg_cache: usize = 32;
/// per-chunk header = make_align(8, sizeof(atomic<cc_t>)=4)
pub const chunk_header_size: usize = 8;
/// sizeof(chunk_info_t)
pub const chunk_info_size: usize = 40;
/// route rc_: low 32 = connection bitmask
pub const route_ep_mask: u64 = 0x00000000ffffffff;
/// route rc_: epoch increment (high 32)
pub const route_ep_incr: u64 = 0x0000000100000000;
/// channel rc_: low 32 = per-reader bitmask
pub const chan_rc_mask: u64 = 0x00000000ffffffff;
/// channel rc_: low 56 = rc bits + internal read-gen
pub const chan_ep_mask: u64 = 0x00ffffffffffffff;
/// channel rc_: epoch increment (top byte)
pub const chan_ep_incr: u64 = 0x0100000000000000;
/// channel rc_: invert-carry mask
pub const chan_ic_mask: u64 = 0xff000000ffffffff;
/// channel rc_: internal read-generation increment (bits 32..)
pub const chan_ic_incr: u64 = 0x0000000100000000;
/// SyncAbi stamp magic "LISA" (0x4C495341)
pub const syncabi_magic: u32 = 1279873857;
/// SyncAbi backend id: apple_ulock
pub const syncabi_backend_ulock: u32 = 2;
/// secure envelope v1 magic
pub const sipc_magic: []const u8 = "SIPC";
/// secure envelope v1 version
pub const sipc_version: u8 = 1;
/// golden fnv1a_64("__IPC_SHM__NOTIFY__xchan") for (prefix="", name="xchan")
pub const notify_hash_xchan: []const u8 = "d7484adebb2d170d";
/// cross-process sync sidecar shm-name suffix for a mutex; full name = <channel-name> + this suffix (byte-exact across all ports)
pub const sync_abi_suffix_mutex: []const u8 = "__thoth_ipc_sync_abi_mutex";
/// cross-process sync sidecar shm-name suffix for a condition variable; full name = <channel-name> + this suffix (byte-exact across all ports)
pub const sync_abi_suffix_condition: []const u8 = "__thoth_ipc_sync_abi_condition";

// --- enums ---
/// typed codec ids
pub const codec_id = enum(u32) {
    flatbuffers = 1,
    protobuf = 2,
    capnp = 3,
};
/// AEAD algorithm ids (SIPC envelope)
pub const secure_alg = enum(u16) {
    aes256gcm = 1,
    chacha20poly1305 = 2,
};

// --- struct layout (byte sizes + field offsets) ---
/// message framing inside a slot's data_ (msg_t<64,8>)
pub const msg_t_size: usize = 80;
pub const msg_t_cc_id_off: usize = 0;
pub const msg_t_id_off: usize = 4;
pub const msg_t_remain_off: usize = 8;
pub const msg_t_storage_off: usize = 12;
pub const msg_t_payload_off: usize = 16;
/// shared conn_head_base + cache-line-aligned prod_cons head; identical offsets for route and channel (block_ starts at size)
pub const ring_header_size: usize = 192;
pub const ring_header_cc_off: usize = 0;
pub const ring_header_lc_off: usize = 4;
pub const ring_header_constructed_off: usize = 8;
pub const ring_header_cursor_off: usize = 64;
pub const ring_header_epoch_off: usize = 128;
/// single-writer route slot (elem_t<80,8>)
pub const route_elem_size: usize = 88;
pub const route_elem_data_off: usize = 0;
pub const route_elem_rc_off: usize = 80;
/// multi-writer channel slot (adds the f_ct_ commit flag)
pub const channel_elem_size: usize = 96;
pub const channel_elem_data_off: usize = 0;
pub const channel_elem_rc_off: usize = 80;
pub const channel_elem_f_ct_off: usize = 88;
/// sizeof(elem_array<route,80,8>) — ftruncate target
pub const route_ring_size: usize = 22784;
/// sizeof(elem_array<channel,80,8>) — ftruncate target
pub const channel_ring_size: usize = 24832;
/// LV_CONN__ owner table entry (32 of them = 512 B)
pub const liveness_slot_size: usize = 16;
pub const liveness_slot_pid_off: usize = 0;
pub const liveness_slot_start_tok_off: usize = 8;
/// secure envelope v1 fixed header (all little-endian)
pub const sipc_header_size: usize = 19;
pub const sipc_header_magic_off: usize = 0;
pub const sipc_header_version_off: usize = 4;
pub const sipc_header_alg_id_off: usize = 5;
pub const sipc_header_key_id_off: usize = 7;
pub const sipc_header_nonce_size_off: usize = 11;
pub const sipc_header_tag_size_off: usize = 13;
pub const sipc_header_ct_size_off: usize = 15;
/// sync ABI guard sidecar (6 x u32)
pub const syncabi_stamp_size: usize = 24;
pub const syncabi_stamp_magic_off: usize = 0;
pub const syncabi_stamp_ver_major_off: usize = 4;
pub const syncabi_stamp_ver_minor_off: usize = 8;
pub const syncabi_stamp_backend_id_off: usize = 12;
pub const syncabi_stamp_primitive_id_off: usize = 16;
pub const syncabi_stamp_payload_size_off: usize = 20;
